name: CLANG build

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  clang-build:
    runs-on: [Windows, ARM64]
    env:
      NO_PERL: 1
    steps:
      - uses: actions/checkout@v3
      - uses: dennisameling/setup-git-for-windows-sdk@a4ceb1b63a115ef2647e58fc8a395a01ef76e343
        with:
          flavor: full
          architecture: aarch64
      - name: Build Git CLANGARM64
        run: make -j`nproc`
