name: CLANG build

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  clang-build:
    runs-on: [Windows, ARM64]
    env:
      NO_PERL: 1
    steps:
      - uses: actions/checkout@v3
      - uses: dennisameling/setup-git-for-windows-sdk@2737d10d8a1c0ca6a09127e71cabb60c7db9fded
        with:
          flavor: full
          architecture: aarch64
      - name: Build Git CLANGARM64
        run: make -j`nproc`
