name: CLANG build

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  clang-build:
    runs-on: [Windows, ARM64]
    env:
      NO_PERL: 1
    steps:
      - uses: actions/checkout@v3
      - uses: dennisameling/setup-git-for-windows-sdk@97cefe96d61d127d483d67fff96c9fc430cf7b19
        with:
          flavor: makepkg-git
          architecture: aarch64
          cleanup: true
      - name: Build Git CLANGARM64
        run: make -j`nproc`
