name: CLANG build

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  clang-build:
    runs-on: [Windows, ARM64]
    env:
      NO_PERL: 1
    steps:
      - uses: actions/checkout@v3
      - uses: dennisameling/setup-git-for-windows-sdk@88fd47fca65647b4644a7580a8469f5a3d80a6d7
        with:
          flavor: full
          architecture: aarch64
      - name: Build Git CLANGARM64
        run: make -j`nproc`
