name: CLANG build

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  clang-build:
    runs-on: [Windows, ARM64]
    env:
      NO_PERL: 1
    steps:
      - uses: dennisameling/setup-git-for-windows-sdk@34977549a33ec5f304dd7bd35a492339c9e52877
        with:
          flavor: full
          architecture: aarch64
      - name: Build Git CLANGARM64
        run: |
          git clone --depth 1 --single-branch -b windows-arm64 https://github.com/dennisameling/MINGW-packages /usr/src/MINGW-packages
          cd /usr/src/MINGW-packages/mingw-w64-git
          MINGW_ARCH=clangarm64 makepkg-mingw
          mkdir -p /artifacts-zst
          cp *.pkg.tar.zst /artifacts-zst
          mkdir -p /artifacts-raw
          cp -ar pkg/ /artifacts-raw
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: git-artifacts-zst
          path: C:/git-sdk-64-full/artifacts-zst
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: git-artifacts-raw
          path: C:/git-sdk-64-full/artifacts-raw
