name: CLANG build

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  clang-build:
    runs-on: [Windows, ARM64]
    env:
      NO_PERL: 1
    steps:
      - uses: actions/checkout@v3
      - uses: dennisameling/setup-git-for-windows-sdk@64780106df88147ed441ef06a8cb9c786c3764be
        with:
          flavor: full
          architecture: aarch64
      - name: Build Git CLANGARM64
        run: make -j`nproc`
